### ISSUE TITLE
min_id and max_id in messages.getHistory()

### ISSUE THREAD

**Issue by MeanSquaredError** [gotd/td#663]
I want to use the min_id and max_id parameters in calls to messages.getHistory(). However after looking into the code it seems that the high-level API in telegram/messages.GetHistory() does not support min_id and max_id.

It seems that the low-level code in tg.MessagesGetHistoryRequest supports these parameters so it should be possible to add support for them in the high-level API.

Is my understanding of the code correct? Are there plans to add support for these two parameters?

**Comment by tdakkota** [comment]
I did not add `min_id` and `max_id` parameters because it can cause some side effects (as I know, Telegram ignores `min_id` and `max_id`, when `offset_id` is used)

I planning to update and refactor `query` package soon:
- Use simple TL-based codegen instead of slow AST-based.
- Split iterator and its internal buffer, to use same code for methods without pagination.
- Rewrite iterator and buffer with generics.
- Add some wrappers/helpers for dialogs and messages.

Generics are upcoming in Go 1.18. According to Go Release Cycle, it will at the beginning of February.

I can add these parameters, but I think it better to use a custom query implementation. You can implement [`messages.Query`](https://pkg.go.dev/github.com/gotd/td/telegram/query/messages#Query) and use it with [`messages.NewIterator`](https://pkg.go.dev/github.com/gotd/td/telegram/query/messages#NewIterator).

**Comment by MeanSquaredError** [comment]
I have been experimenting with the low-level tg.* functions downloading history messages from channels and so far my experiments show that `min_id` and `max_id` are not really ignored but rather work as additional filter applied on the server after results have been selected by `offset_id`, `add_offset` and `limit`

So let's say that there is some channel with messages with IDs ranging from 1000 to 1 and that they don't have any gaps in their numbering.

If you pass `offset_id=920, add_offset=1, limit=10` then the server will return ten messages with ID's `919, 918, ..., 910`

However if you send a query with `offset_id=920, add_offset=1, limit=10, max_id=917, min_id=911`, then you will get only five messages with IDs `916, 915, 914, 913, 912`

Or if you send a query with `offset_id=920, add_offset=1, limit=10, max_id=812, min_id=750` then you will get zero messages because the initial `offset_id=920, add_offset=1, limit=10` will select messages from 919 to 910 and afterwards `max_id=812, min_id=750` will remove all the selected messages from the list as not matching the range `750 < message_id < 812`.

Overall `max_id` is not very useful but `min_id` can be used when downloading large ranges of messages, e.g. when filling gaps in downloaded messages, e.g. when one needs to remove all messages with ID less than a certain number because they have been already downloaded.

However all of the above information is from my experiments so it may be incorrect and/or incomplete.

I decided to use the low-level functions in tg.* anyway because the high-level iterators in telegram.Messages().Foreach() make it difficult to limit server-requests and react to flood_wait errors.

Other than that I can say that overall gotd is a rather useful library so thank you for developing and maintaining it.
